### PR TITLE
Fix deploy preview

### PR DESCRIPTION
**Pull request by shawna-slh**
like this https://github.com/w3c/wai-accessibility-principles/pull/36/commits/488292cc27b389ec5b2e64fdce76c180dd7036d5

### CODE REVIEW

**Comment by SteveALee** [comment]
@slhenry fixed  - deploy build seems to have been out of date for a long time :(

**Comment by SteveALee** [comment]
@slhenry here's the [preview link](https://5fd9dffe991d46000838de7f--wai-involveusersall.netlify.app/planning/involving-users/) not sure why not shown above.

**Comment by SteveALee** [comment]
I quess this PR can be closed

**Comment by shawna-slh** [comment]
Steve: looks like you just created to test and  I made all the same fixes to #12 too. Thus just close?

**Pull request closed without merging**
